project:
  type: website
  output-dir: docs

website:
  title: "Erick Figueroa Ildefonso"
  navbar:
    #title: "My personal website"
    #logo: /images/SA_cougar.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: My Blog
        href: posts.qmd
  #    - text: Email
  #      href: mailto:erick.figueroa@duke.edu
   
#    tools: 
#      - icon: github
#        href: https://github.com/erickfigue
#        target: _blank
#      - icon: twitter
#        href: https://twitter.com/EFigueroaI
#        target: _blank
#      - icon: linkedin
#        href: https://linkedin.com/in/e-figueroa-i
#        target: _blank
#      - icon: instagram
#        href: https://www.instagram.com/e.figueroa.i
#       target: _blank

      

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: Sylfaen
    fontsize: 1rem
    fontcolor: "#4d6e91"
    linkcolor: "#093163"
    monofont: courier new
    css: styles.css
    toc: true
    #grid: 
     # margin-width: 50px
      #sidebar-width: 500px
      #body-width: 1000px
    page-layout: article
    
editor: visual

